In [1]:
import numpy as np 
def create_anchors_3d_stride(feature_size,
                             sizes=[1.6, 3.9, 1.56],
                             anchor_strides=[0.4, 0.4, 0.0],
                             anchor_offsets=[0.2, -39.8, -1.78],
                             rotations=[0, np.pi / 2],
                             dtype=np.float32):
    """
    Args:
        feature_size: list [D, H, W](zyx)
        sizes: [N, 3] list of list or array, size of anchors, xyz

    Returns:
        anchors: [*feature_size, num_sizes, num_rots, 7] tensor.
    """
    # almost 2x faster than v1
    x_stride, y_stride, z_stride = anchor_strides
    x_offset, y_offset, z_offset = anchor_offsets
    z_centers = np.arange(feature_size[0], dtype=dtype)
    y_centers = np.arange(feature_size[1], dtype=dtype)
    x_centers = np.arange(feature_size[2], dtype=dtype)
    z_centers = z_centers * z_stride + z_offset
    y_centers = y_centers * y_stride + y_offset
    x_centers = x_centers * x_stride + x_offset
    sizes = np.reshape(np.array(sizes, dtype=dtype), [-1, 3])
    rotations = np.array(rotations, dtype=dtype)
    rets = np.meshgrid(
        x_centers, y_centers, z_centers, rotations, indexing='ij')
    tile_shape = [1] * 5
    tile_shape[-2] = int(sizes.shape[0])
    for i in range(len(rets)):
        rets[i] = np.tile(rets[i][..., np.newaxis, :], tile_shape)
        rets[i] = rets[i][..., np.newaxis]  # for concat
    sizes = np.reshape(sizes, [1, 1, 1, -1, 1, 3])
    tile_size_shape = list(rets[0].shape)
    tile_size_shape[3] = 1
    sizes = np.tile(sizes, tile_size_shape)
    rets.insert(3, sizes)
    ret = np.concatenate(rets, axis=-1)
    return np.transpose(ret, [2, 1, 0, 3, 4, 5])


In [6]:
    feature_size =  [1,200,176]
    sizes=[1.6, 3.9, 1.56]
    anchor_strides=[0.4, 0.4, 1.0]
    anchor_offsets=[0.2, -39.8, -1.78]
    rotations=[0, np.pi / 2]
    class_id=None
    match_threshold=-1
    unmatch_threshold=-1
    dtype = np.float32

In [7]:
    x_stride, y_stride, z_stride = anchor_strides
    x_offset, y_offset, z_offset = anchor_offsets
    z_centers = np.arange(feature_size[0], dtype=dtype)
    y_centers = np.arange(feature_size[1], dtype=dtype)
    x_centers = np.arange(feature_size[2], dtype=dtype)
    z_centers = z_centers * z_stride + z_offset
    y_centers = y_centers * y_stride + y_offset
    x_centers = x_centers * x_stride + x_offset

In [14]:
x_centers.shape

(176,)

In [15]:
    sizes = np.reshape(np.array(sizes, dtype=dtype), [-1, 3])
    rotations = np.array(rotations, dtype=dtype)
    rets = np.meshgrid(
        x_centers, y_centers, z_centers, rotations, indexing='ij')
    tile_shape = [1] * 5
    tile_shape[-2] = int(sizes.shape[0])

In [22]:
rets[3].shape

(176, 200, 1, 2)

In [24]:
for i in range(len(rets)):
    rets[i] = np.tile(rets[i][..., np.newaxis, :], tile_shape)
    rets[i] = rets[i][..., np.newaxis]  # for concat

In [25]:
rets[0].shape

(176, 200, 1, 1, 2, 1)

In [27]:
sizes = np.reshape(sizes, [1, 1, 1, -1, 1, 3])
tile_size_shape = list(rets[0].shape)
tile_size_shape[3] = 1
sizes = np.tile(sizes, tile_size_shape)

In [28]:
sizes.shape

(176, 200, 1, 1, 2, 3)

In [29]:
rets.insert(3, sizes)

In [31]:
len(rets)

5

In [34]:
rets[3].shape

(176, 200, 1, 1, 2, 3)

In [35]:
ret = np.concatenate(rets, axis=-1)

In [36]:
ret = np.transpose(ret, [2, 1, 0, 3, 4, 5])

In [37]:
ret.shape

(1, 200, 176, 1, 2, 7)

In [39]:
ret[0].shape

(200, 176, 1, 2, 7)

In [40]:
ret[0][0,0,0,0,:]

array([  0.2 , -39.8 ,  -1.78,   1.6 ,   3.9 ,   1.56,   0.  ],
      dtype=float32)

In [41]:
ret[0][0,0,0,:,0]

array([0.2, 0.2], dtype=float32)

In [42]:
ret[0][:,0,0,0,0]

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2,
       0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.

In [43]:
ret[0][0,:,0,0,0]

array([ 0.2      ,  0.6      ,  1.       ,  1.4000001,  1.8000001,
        2.2      ,  2.6000001,  3.       ,  3.4      ,  3.8000002,
        4.2      ,  4.6      ,  5.       ,  5.4      ,  5.7999997,
        6.2      ,  6.6      ,  7.       ,  7.4      ,  7.7999997,
        8.2      ,  8.6      ,  9.       ,  9.4      ,  9.8      ,
       10.2      , 10.6      , 11.       , 11.4      , 11.8      ,
       12.2      , 12.6      , 13.       , 13.4      , 13.8      ,
       14.2      , 14.6      , 15.       , 15.4      , 15.8      ,
       16.2      , 16.6      , 17.000002 , 17.400002 , 17.800001 ,
       18.2      , 18.6      , 19.000002 , 19.400002 , 19.800001 ,
       20.2      , 20.6      , 21.000002 , 21.400002 , 21.800001 ,
       22.2      , 22.6      , 23.000002 , 23.400002 , 23.800001 ,
       24.2      , 24.6      , 25.000002 , 25.400002 , 25.800001 ,
       26.2      , 26.6      , 27.000002 , 27.400002 , 27.800001 ,
       28.2      , 28.6      , 29.000002 , 29.400002 , 29.8000

In [45]:
anchors = ret.reshape([*ret.shape[:3], -1, 7])

In [46]:
anchors.shape

(1, 200, 176, 2, 7)

In [47]:
# dataset.py ==> class KittiDataset(Dataset):
anchors = anchors.reshape([-1, 7])
# matched_thresholds = ret["matched_thresholds"]
# unmatched_thresholds = ret["unmatched_thresholds"]

In [49]:
anchors.shape

(70400, 7)

In [51]:
import vis 

array([  0.2      , -39.8      ,  -1.78     ,   1.6      ,   3.9      ,
         1.56     ,   1.5707964], dtype=float32)

In [ ]:
anchors_mask = None
if anchor_area_threshold >= 0:
    coors = coordinates
    dense_voxel_map = box_np_ops.sparse_sum_for_anchors_mask(
        coors, tuple(grid_size[::-1][1:]))
    dense_voxel_map = dense_voxel_map.cumsum(0)
    dense_voxel_map = dense_voxel_map.cumsum(1)
    anchors_area = box_np_ops.fused_get_anchors_area(
        dense_voxel_map, anchors_bv, voxel_size, pc_range, grid_size)
    anchors_mask = anchors_area > anchor_area_threshold
    # example['anchors_mask'] = anchors_mask.astype(np.uint8)
    example['anchors_mask'] = anchors_mask