In [1]:
import numpy as np
import ops 
import v2

In [2]:
points,p2,rect,Trv2c,image_shape,annos = v2.load()

In [4]:
points.shape

(108348, 4)

In [5]:
p2

array([[7.215377e+02, 0.000000e+00, 6.095593e+02, 4.485728e+01],
       [0.000000e+00, 7.215377e+02, 1.728540e+02, 2.163791e-01],
       [0.000000e+00, 0.000000e+00, 1.000000e+00, 2.745884e-03],
       [0.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00]])

In [6]:
rect

array([[ 0.9999239 ,  0.00983776, -0.00744505,  0.        ],
       [-0.0098698 ,  0.9999421 , -0.00427846,  0.        ],
       [ 0.00740253,  0.00435161,  0.9999631 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [7]:
Trv2c

array([[ 7.533745e-03, -9.999714e-01, -6.166020e-04, -4.069766e-03],
       [ 1.480249e-02,  7.280733e-04, -9.998902e-01, -7.631618e-02],
       [ 9.998621e-01,  7.523790e-03,  1.480755e-02, -2.717806e-01],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00]])

In [8]:
image_shape

array([ 375, 1242], dtype=int32)

In [9]:
annos

{'name': array(['Car', 'Car', 'Car', 'Car', 'Van'], dtype='<U3'),
 'truncated': array([0.  , 0.  , 0.99, 0.  , 0.  ]),
 'occluded': array([0, 0, 1, 0, 2]),
 'alpha': array([-1.75, -1.31, -2.37, -1.58, -1.24]),
 'bbox': array([[ 683.34,  170.98,  803.44,  257.43],
        [ 262.97,  182.23,  469.76,  318.  ],
        [ 910.25,  159.81, 1241.  ,  374.  ],
        [ 641.55,  172.79,  681.44,  206.29],
        [ 683.63,  153.82,  724.01,  183.67]]),
 'dimensions': array([[4.34, 1.49, 1.56],
        [4.12, 1.42, 1.53],
        [3.89, 1.59, 1.59],
        [3.51, 1.38, 1.64],
        [5.33, 2.59, 1.98]]),
 'location': array([[ 2.51,  1.49, 14.75],
        [-3.06,  1.56,  9.79],
        [ 2.61,  1.55,  2.39],
        [ 2.22,  1.4 , 31.72],
        [ 8.59,  0.95, 65.64]]),
 'rotation_y': array([-1.59, -1.61, -1.6 , -1.51, -1.11]),
 'score': array([0., 0., 0., 0., 0.]),
 'index': array([0, 1, 2, 3, 4], dtype=int32),
 'group_ids': array([0, 1, 2, 3, 4], dtype=int32)}

In [10]:
gt_cam = annos['location']
center_point = ops.camera_to_lidar(gt_cam,rect,Trv2c)
np.savetxt('center_point.txt',center_point)

In [11]:
center_point

array([[15.03825643, -2.49425244, -1.43447899],
       [10.0779512 ,  3.07555948, -1.49747116],
       [ 2.67958218, -2.59515009, -1.62470683],
       [32.00632071, -2.20310901, -1.16406688],
       [65.92126071, -8.57328949, -0.42689766]])

In [52]:
points

array([[ 6.2427e+01,  3.2000e-02,  2.3200e+00,  0.0000e+00],
       [ 6.2368e+01,  2.2800e-01,  2.3180e+00,  0.0000e+00],
       [ 6.2375e+01,  4.2400e-01,  2.3180e+00,  0.0000e+00],
       ...,
       [ 3.5810e+00, -1.3470e+00, -1.6680e+00,  2.1000e-01],
       [ 3.5330e+00, -1.3160e+00, -1.6420e+00,  7.0000e-02],
       [ 3.6110e+00, -1.3390e+00, -1.6800e+00,  0.0000e+00]],
      dtype=float32)

In [54]:
w,h,l = annos['dimensions'][:,0],annos['dimensions'][:,1],annos['dimensions'][:,2]

In [56]:
x,y,z = annos['location'][:,0],annos['location'][:,1],annos['location'][:,2]

In [57]:
ry = annos['rotation_y']

In [59]:
R = np.array([ [+np.cos(ry), 0, +np.sin(ry)],
                 [0, 1,               0],
                 [-np.sin(ry), 0, +np.cos(ry)] ] )

In [62]:
corner_norm = np.array()



x_corners = np.array([0, l, l, l, l, 0, 0, 0]*5).reshape(-1,8) # -l/2
y_corners = np.array([0, 0, h, h, 0, 0, h, h]*5).reshape(-1,8) # -h
z_corners = np.array([0, 0, 0, w, w, w, w, 0]*5).reshape(-1,8)# --w/2

x_corners += -l/2
y_corners += -h
z_corners += -w/2

ValueError: operands could not be broadcast together with shapes (5,8) (5,) (5,8) 

In [113]:
corners_norm = np.array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1], dtype=dims.dtype).reshape((8, 3))
corners_norm = corners_norm[[0, 1, 3, 2, 4, 5, 7, 6]]
whl = annos['dimensions']
lhw = whl[:,[2,1,0]]
whl = lhw
corners = whl.reshape(-1,1,3) * corners_norm.reshape(1,-1,3)
corners[:,:,0] -= whl[:,0].reshape(-1,1)/2
corners[:,:,1] -= whl[:,1].reshape(-1,1)
corners[:,:,2] -= whl[:,2].reshape(-1,1)/2


In [114]:

corners += annos['location'].reshape([-1, 1, 3])

In [115]:
corners = ops.camera_to_lidar(corners,rect,Trv2c)

np.savetxt('corners.txt',corners.reshape(-1,3))

In [116]:
corners_norm

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 0.]])

In [117]:
conrners_norm  = np.array([[0., 0., 0.],
                               [0., 0., 1.],
                               [0., 1., 1.],
                               [0., 1., 0.],
                               [1., 0., 0.],
                               [1., 0., 1.],
                               [1., 1., 1.],
                               [1., 1., 0.]])

In [118]:
conrners_norm

array([[0., 0., 0.],
       [0., 0., 1.],
       [0., 1., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 0.]])

In [119]:
import ops

In [3]:
whl = annos['dimensions']
loc = annos['location']
convers = ops.label_to_lidar_3dbox(whl,loc ,rect,Trv2c)

In [7]:
convers[0]

array([[12.85262225, -1.73030821,  0.0409167 ],
       [17.19238513, -1.72976846,  0.08627536],
       [17.20795475, -1.71402609, -1.40356014],
       [12.86819187, -1.71456583, -1.4489188 ],
       [12.8529885 , -3.29022116,  0.02443767],
       [17.19275138, -3.28968142,  0.06979633],
       [17.20832099, -3.27393904, -1.42003917],
       [12.86855812, -3.27447879, -1.46539783]])

In [50]:
import numba
def corner_to_surfaces_3d(corners):
    """convert 3d box corners from corner function above
    to surfaces that normal vectors all direct to internal.

    Args:
        corners (float array, [N, 8, 3]): 3d box corners. 
    Returns:
        surfaces (float array, [N, 6, 4, 3]): 
    """
    # box_corners: [N, 8, 3], must from corner functions in this module
    surfaces = np.array([
        [corners[:, 0], corners[:, 1], corners[:, 2], corners[:, 3]],
        [corners[:, 7], corners[:, 6], corners[:, 5], corners[:, 4]],
        [corners[:, 0], corners[:, 3], corners[:, 7], corners[:, 4]],
        [corners[:, 1], corners[:, 5], corners[:, 6], corners[:, 2]],
        [corners[:, 0], corners[:, 4], corners[:, 5], corners[:, 1]],
        [corners[:, 3], corners[:, 2], corners[:, 6], corners[:, 7]],
    ]).transpose([2, 0, 1, 3])
    return surfaces


def surface_equ_3d_jit(polygon_surfaces):
    # return [a, b, c], d in ax+by+cz+d=0
    # polygon_surfaces: [num_polygon, num_surfaces, num_points_of_polygon, 3]
    surface_vec = polygon_surfaces[:, :, :2, :] - polygon_surfaces[:, :, 1:3, :]
    # normal_vec: [..., 3]
    normal_vec = np.cross(surface_vec[:, :, 0, :], surface_vec[:, :, 1, :])
    # print(normal_vec.shape, points[..., 0, :].shape)
    # d = -np.inner(normal_vec, points[..., 0, :])
    d = np.einsum('aij, aij->ai', normal_vec, polygon_surfaces[:, :, 0, :])
    return normal_vec, -d

@numba.jit(nopython=False)
def points_in_convex_polygon_3d_jit(points,
                                    polygon_surfaces,
                                    num_surfaces=None):
    """check points is in 3d convex polygons.
    Args:
        points: [num_points, 3] array.
        polygon_surfaces: [num_polygon, max_num_surfaces, 
            max_num_points_of_surface, 3] 
            array. all surfaces' normal vector must direct to internal.
            max_num_points_of_surface must at least 3.
        num_surfaces: [num_polygon] array. indicate how many surfaces 
            a polygon contain
    Returns:
        [num_points, num_polygon] bool array.
    """
    max_num_surfaces, max_num_points_of_surface = polygon_surfaces.shape[1:3]
    num_points = points.shape[0]
    num_polygons = polygon_surfaces.shape[0]
    if num_surfaces is None:
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])
    # normal_vec: [num_polygon, max_num_surfaces, 3]
    # d: [num_polygon, max_num_surfaces]
    ret = np.ones((num_points, num_polygons), dtype=np.bool_)
    sign = 0.0
    for i in range(num_points):
        for j in range(num_polygons):
            for k in range(max_num_surfaces):
                if k > num_surfaces[j]:
                    break
                sign = points[i, 0] * normal_vec[j, k, 0] \
                     + points[i, 1] * normal_vec[j, k, 1] \
                     + points[i, 2] * normal_vec[j, k, 2] + d[j, k]
                if sign >= 0:
                    ret[i, j] = False
                    break
    return ret

In [17]:
convers.shape

(5, 8, 3)

In [18]:
surfaces = corner_to_surfaces_3d(convers)

In [19]:
normal_vec,neg_d =  surface_equ_3d_jit(surfaces)

In [31]:
import time

In [26]:
points.shape

(108348, 4)

In [51]:
a = time.time()
ret = points_in_convex_polygon_3d_jit(points,surfaces)
b = time.time()-a
print(b)

<ipython-input-50-aaaeab05dc6d>:34: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Untyped global name 'surface_equ_3d_jit': cannot determine Numba type of <class 'function'>

File "<ipython-input-50-aaaeab05dc6d>", line 55:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
        num_surfaces = np.full((num_polygons,), 9999999, dtype=np.int64)
    normal_vec, d = surface_equ_3d_jit(polygon_surfaces[:, :, :3, :])
    ^

  @numba.jit(nopython=False)
<ipython-input-50-aaaeab05dc6d>:34: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "points_in_convex_polygon_3d_jit" failed type inference due to: Untyped global name 'surface_equ_3d_jit': cannot determine Numba type of <class 'function'>

File "<ipython-input-50-aaaeab05dc6d>", line 55:
def points_in_convex_polygon_3d_jit(points,
    <source elided>
      

0.6981499195098877


In [28]:
len(ret)

108348

In [96]:
ret.sum(0).sum()

3460

In [32]:
ret.shape

(108348, 5)

In [33]:
points.shape

(108348, 4)

In [41]:
ret_4 = ret[:,np.newaxis*5,:]

In [35]:
points[ret]

IndexError: boolean index did not match indexed array along dimension 1; dimension is 4 but corresponding boolean dimension is 5

In [62]:
ret.shape

(108348, 5)

In [84]:
obj = np.zeros((1,4))
for i in range(5):
    obj = np.concatenate((obj,points[ret[:,i]]))

In [87]:
np.savetxt('obj.txt',obj[1:])

In [81]:
b.shape

(216696, 5)

In [75]:
ret.shape

(108348, 5)

In [88]:
points.shape

(108348, 4)

In [100]:
pts = np.repeat(points,5,axis=0).reshape(-1,5,4)

In [92]:
pts = pts.reshape(-1,5,4)

In [101]:
a = pts[ret]

In [102]:
a.shape

(3460, 4)

In [103]:
np.savetxt('a.txt',a)